--- #gameoflife assignment

- hosts: qa
  connection: ssh
  become: yes
  user: ansible
  gather_facts: yes

  tasks:

   - name: installing java
     action: yum pkg=java-1.8.0-openjdk-devel.x86_64 state=present


   - name: download tomcat
     get_url:
       url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.63/bin/apache-tomcat-9.0.63.zip
       dest: /home/ansible/

   - name: Unarchive
     ansible.builtin.unarchive:
       src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.63/bin/apache-tomcat-9.0.63.zip
       dest: /home/ansible/
       remote_src: yes


   - name: permit
     command: sudo chmod -R 777 apache-tomcat-9.0.63

   - name: start tomcat
     command: nohup /home/ansible/apache-tomcat-9.0.63/bin/startup.sh

    - name: copy-from-s3
      command: aws s3 cp s3://jnv-bucket/loginwebapp.war .

   - name: deployment
     action: copy src=loginwebapp.war dest=/home/ansible/apache-tomcat-9.0.63/webapps



